<a href="https://colab.research.google.com/github/StaticDoDoubleG/PSTP_Workspace/blob/main/0628_Array_and_LinkedList.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **배열**

In [7]:
a = list() #빈 리스트
print(a)

for i in range(4):
  aa= int(input(f"index[{i}] 위치에 추가할 값:")) #합쳐도 됨
  a.append(aa)
  print(f"리스트:{a}")


[]
index[0] 위치에 추가할 값:4
리스트:[4]
index[1] 위치에 추가할 값:8
리스트:[4, 8]
index[2] 위치에 추가할 값:9
리스트:[4, 8, 9]
index[3] 위치에 추가할 값:10
리스트:[4, 8, 9, 10]


In [11]:
#리스트변수명.insert(인덱스번호, 우리가 넣고 싶은 값)
print(f"리스트{a}")

#a.insert(2, 50)

while (1):  # 무한 반복
  idx = input("인덱스 위치 선택: ")

  if idx == ' ':
    print("스페이스키를 눌러 종료합니다.")
    break

  value = int(input(f"{idx} 위치에 넣을 값: "))
  a.insert(int(idx), value)
  print(a)


리스트[4, 20, '20', 8, 9, 10]
인덱스 위치 선택: 0
0 위치에 넣을 값: 100
[100, 4, 20, '20', 8, 9, 10]
인덱스 위치 선택:  
스페이스키를 눌러 종료합니다.


In [25]:
lista =[8, 4, 9, 10]
print(f'리스트: {lista}')

'''
리스트명.pop(인덱스 번호) //삭제한 값을 알려줌
리스트명.remove(삭제하고 싶은 실제 값) //삭제한 값을 알려주지 않음
리스트명.delete(리스트명[인덱스번호]) //삭제한 값을 알려주지 않음
'''
while(1):
  select = int(input("삭제의 방법 선택\n1. pop\n2. remove\n3. del\n0. 종료\n"))
  if select == 0:
    print("종료")
    break #특정한 탈출 조건을 두는게 좋음

  if select == 1: #pop
    idx = int(input("삭제를 원하는 인덱스는? "))
    result = lista.pop(idx)
    print(f"삭제한 값: {result} ")
    print(lista)

  elif select == 2: #remove
    print(lista) #현재의 리스트 결과값을 보여줌
    rm = int(input("삭제를 원하는 값은? "))
    lista.remove(rm)
    print(lista) #삭제 후 리스트 결과값 보여줌

  elif select == 3: #delete
    print(lista) #현재의 리스트에서의 결과값을 보여줌
    idx = int(input("삭제를 원하는 인덱스는? "))
    del(lista[idx])
    print(lista) #삭제 이후의 리스트에서의 결과값을 보여줌





리스트: [8, 4, 9, 10]
삭제의 방법 선택
1. pop
2. remove
3. del
0. 종료
0
종료


In [ ]:
list_2 = [
    [1, 2, 3],
    [4, 5, 6]
] #2차원배열 /2차원 리스트

In [28]:
a = [1, 2, 3]
b = [4, 5, 6]
print(a + b)

[1, 2, 3, 4, 5, 6]


In [27]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(f'a = \n {a}')
b = np.array([[5, 6, 7], [8, 9, 10]])
print(f'b = \n {b}')
c = a + b
print(f' a+b = \n {a + b}')

a = 
 [[1 2 3]
 [4 5 6]]
b = 
 [[ 5  6  7]
 [ 8  9 10]]
 a+b = 
 [[ 6  8 10]
 [12 14 16]]


In [30]:
bb = np.array([[1, 2, 3]])
cc = np.array([[4], [5], [6]])
print(bb)
print(cc)
bb.dot(cc)

[[1 2 3]]
[[4]
 [5]
 [6]]


array([[32]])

In [31]:
dd = np.array([[1, 2, 3], [4, 5, 6]])
ee = np.array([[1, 2], [3, 4], [5, 6]])
dd.dot(ee)

array([[22, 28],
       [49, 64]])

In [35]:
dd = np.array([[1, 2, 3], [4, 5, 6]]) #2 * 3
print(dd.reshape(3, 2)) #3행 2열

[[1 2]
 [3 4]
 [5 6]]


In [36]:
print(dd)

[[1 2 3]
 [4 5 6]]


In [37]:
dd[1][1] = 50
print(dd)

[[ 1  2  3]
 [ 4 50  6]]


In [44]:
np.zeros(5)
np.zeros((3, 2))
np.ones(7)
np.ones((3, 3))
np.random.rand(2, 3)

array([[0.88736335, 0.81946877, 0.75811181],
       [0.31195475, 0.7523707 , 0.9960162 ]])

# **연결 리스트**

In [47]:
linka = {8:[65, 4], 4:[54, 9], 9:[12, None]}
print(linka)

#함수 정의
def SL(linka, root):
  head = root
  next_node = head

  while (1):
    node_value = linka[next_node][0] #데이터 값
    next_node = linka[next_node][1]  #다음 주소
    print(f"데이터 값: {node_value}")
    if next_node == None:
      break

  '''
  while next_node != None:
    node_value = linka[next_node][0] #데이터 값
    next_node = linka[next_node][1]  #다음 주소
    print(f"데이터 값: {node_value}")
  '''

#함수 호출
SL(linka, 8) #(, 처음 시작 값인 헤드)

{8: [65, 4], 4: [54, 9], 9: [12, None]}
데이터 값: 65
데이터 값: 54
데이터 값: 12


퀴즈 3 대체과제

In [54]:
a = {'head':['일', 65], 65:['월', 54], 54:['화', 12], 12:['수', 117],
     117:['목', 80], 80:['금', 31], 31:['토', None]}
print(a)

def SinglyLinkedList(slist, root):
  head = root
  next_node = head
  print("head{시작} :", next_node)
  while(1):
    node_value = slist[next_node][0]
    next_node = slist[next_node][1]
    print(f'value: {node_value}')
    print(f'next: {next_node}')
    if next_node == None:
      break

SinglyLinkedList(a, 'head')


{'head': ['일', 65], 65: ['월', 54], 54: ['화', 12], 12: ['수', 117], 117: ['목', 80], 80: ['금', 31], 31: ['토', None]}
head{시작} : head
value: 일
next: 65
value: 월
next: 54
value: 화
next: 12
value: 수
next: 117
value: 목
next: 80
value: 금
next: 31
value: 토
next: None
